### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by sconklin** [dkozel/dkozel.github.io#3]
On the about page, the link to your github repo is broken due to an extra 'g' at the end.

The link to hugo-smorg is 404

**Comment by bekopharm** [comment]
Fun. Stumbled over this as well: https://github.com/dkozel/dkozel.github.io/blob/c5c37c57ec491ea1260631ae2ba41e9cb058e86b/index.html#L122

**Comment by dkozel** [comment]
Not sure when I fixed this, but it's done now for sure! Thanks for pointing it out.
